import type { Metadata } from 'next'
import { Inter, Recursive } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import Footer from '@/components/Footer'
import { Toaster } from '@/components/ui/toaster'
import Providers from '@/components/Providers'

const recursive = Recursive({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={recursive.className}>
          <Providers>
            <Navbar />
            <main className="flex flex-col grainy-light min-h-[calc(100vh-114px)]">
              <div className="flex-1 flex flex-col h-full items-center justify-center ">
                {children}
              </div>
            </main>
          </Providers>
          <Footer />
          <Toaster />
        </body>
      </SessionProvider>
    </html>
  )
}
